//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_FrameWork_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ÖrnekKitapListesi
    {
        public int Sıra { get; set; }
        public string KitapAdı { get; set; }
        public string Yazar { get; set; }
        public string Yayınevi { get; set; }
    }
}
